### ISSUE TITLE
hang at telnet task

### ISSUE THREAD

**Issue by vvuk** [unxmaal/irix_ansible#13]
I think I'm missing something here -- the README instructions don't say anything about how to specify what the target actually _is_.  I assume this comes from the ansible inventory, i.e. the `challenge` hostname in the default.  If I change that to my target's hostname (`indy`) & set its ip address in `ansible_host`, I get a hang at:

```
...
TASK [bootstrap : Hard-set date and time on SGI based on host system] 
```

if I add some code to dump the python telnet lib output, it's connecting, and reading `Password:` but never actually sending anything after that.  Ansible 2.9.6 with python 3.8.10 on Ubuntu 20.04 LTS.

**Comment by vvuk** [comment]
Ah!  So the default for `password_prompt` is `"Password: "`.  IRIX 6.5.22 is only sending `"Password:"` (no space).  So the task never sees the password prompt.

**Comment by vvuk** [comment]
Actually no -- the issue seems to be the empty password.  I can't get ansible to send an empty password; it just hangs at the password prompt, regardless of what `password_prompt` is set to.  If I set a password and the manually modify every `password: ` in the bootstrap tasks to include it, things move forward.

**Comment by unxmaal** [comment]
Standard practice is to run ansible vs a "target" host. That host is specified in the inventory.yml .  You should change all of the values in the inventory.yml to match your network. The hostname 'challenge' is not really a value, but you can change it too. It won't matter to ansible, as it's just a way for ansible to group host-specific values.

At a higher level: do not run these plays without deeply understanding what they do. They're tailored to set up _my system_ in the way that I like it to be set up. There's zero guarantee that your system can be set up in this same way -- and since the OS is a different version, I'd find it highly unlikely.

If this is NOT your third or tenth time reinstalling IRIX on this system, you should just use these plays as a reference for "how to do xyz". Write down which ones you did, which ones worked, and which ones needed modification. Then create your own plays for your own system, so that you can quickly get your system back up and running the way you like it when you need to reinstall.
